# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pilipinas` gem.
# Please instead update this file by running `bin/tapioca gem pilipinas`.


# source://pilipinas//lib/pilipinas/railtie.rb#4
module MyGem; end

# source://pilipinas//lib/pilipinas/railtie.rb#5
class MyGem::Railtie < ::Rails::Railtie; end

# source://pilipinas//lib/pilipinas/version.rb#1
module Pilipinas; end

# source://pilipinas//lib/pilipinas/barangay.rb#2
class Pilipinas::Barangay < ::Pilipinas::Base
  class << self
    # source://pilipinas//lib/pilipinas/barangay.rb#4
    def load_data; end
  end
end

# source://pilipinas//lib/pilipinas/base.rb#2
class Pilipinas::Base
  # @return [Base] a new instance of Base
  #
  # source://pilipinas//lib/pilipinas/base.rb#8
  def initialize(options = T.unsafe(nil)); end

  # Returns the value of attribute code.
  #
  # source://pilipinas//lib/pilipinas/base.rb#3
  def code; end

  # Returns the value of attribute name.
  #
  # source://pilipinas//lib/pilipinas/base.rb#3
  def name; end

  class << self
    # source://pilipinas//lib/pilipinas/base.rb#63
    def add(region); end

    # source://pilipinas//lib/pilipinas/base.rb#35
    def all; end

    # source://pilipinas//lib/pilipinas/base.rb#16
    def assoc_collection(options); end

    # source://pilipinas//lib/pilipinas/base.rb#23
    def count; end

    # Returns the value of attribute data.
    #
    # source://pilipinas//lib/pilipinas/base.rb#14
    def data; end

    # Sets the attribute data
    #
    # @param value the value to set the attribute data to.
    #
    # source://pilipinas//lib/pilipinas/base.rb#14
    def data=(_arg0); end

    # source://pilipinas//lib/pilipinas/base.rb#43
    def find_by(options); end

    # source://pilipinas//lib/pilipinas/base.rb#27
    def first; end

    # source://pilipinas//lib/pilipinas/base.rb#31
    def last; end

    # source://pilipinas//lib/pilipinas/base.rb#39
    def load_data; end

    # source://pilipinas//lib/pilipinas/base.rb#56
    def load_file(file); end

    # source://pilipinas//lib/pilipinas/base.rb#48
    def method_missing(*args); end

    # @raise [Pilipinas::UnknownAttribute]
    #
    # source://pilipinas//lib/pilipinas/base.rb#76
    def parse_attributes(attr, val); end

    # source://pilipinas//lib/pilipinas/base.rb#86
    def reset_data; end

    # source://pilipinas//lib/pilipinas/base.rb#68
    def select_by(attribute, val); end

    # source://pilipinas//lib/pilipinas/base.rb#82
    def validate(obj); end

    private

    def new(*_arg0); end
  end
end

# source://pilipinas//lib/pilipinas/city.rb#2
class Pilipinas::City < ::Pilipinas::Base
  # source://pilipinas//lib/pilipinas/city.rb#3
  def barangays; end

  class << self
    # source://pilipinas//lib/pilipinas/city.rb#8
    def load_data; end
  end
end

# source://pilipinas//lib/pilipinas.rb#17
module Pilipinas::Db; end

# source://pilipinas//lib/pilipinas/db/barangay.rb#3
class Pilipinas::Db::Barangay < ::ActiveRecord::Base
  include ::Pilipinas::Db::Barangay::GeneratedAttributeMethods
  include ::Pilipinas::Db::Barangay::GeneratedAssociationMethods

  # source://activerecord/7.2.2.1/lib/active_record/autosave_association.rb#162
  def autosave_associated_records_for_city(*args); end

  class << self
    # source://activesupport/7.2.2.1/lib/active_support/callbacks.rb#70
    def __callbacks; end

    # source://activerecord/7.2.2.1/lib/active_record/reflection.rb#11
    def _reflections; end

    # source://activemodel/7.2.2.1/lib/active_model/validations.rb#71
    def _validators; end

    # source://activerecord/7.2.2.1/lib/active_record/enum.rb#167
    def defined_enums; end
  end
end

# source://pilipinas//lib/pilipinas/db/barangay.rb#0
module Pilipinas::Db::Barangay::GeneratedAssociationMethods
  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#32
  def build_city(*args, &block); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#103
  def city; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#111
  def city=(value); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/belongs_to.rb#146
  def city_changed?; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/belongs_to.rb#150
  def city_previously_changed?; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#36
  def create_city(*args, &block); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#40
  def create_city!(*args, &block); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#19
  def reload_city; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#23
  def reset_city; end
end

# source://pilipinas//lib/pilipinas/db/barangay.rb#0
module Pilipinas::Db::Barangay::GeneratedAttributeMethods; end

# source://pilipinas//lib/pilipinas/db/city.rb#3
class Pilipinas::Db::City < ::ActiveRecord::Base
  include ::Pilipinas::Db::City::GeneratedAttributeMethods
  include ::Pilipinas::Db::City::GeneratedAssociationMethods

  # source://activerecord/7.2.2.1/lib/active_record/autosave_association.rb#162
  def autosave_associated_records_for_barangays(*args); end

  # source://activerecord/7.2.2.1/lib/active_record/autosave_association.rb#162
  def autosave_associated_records_for_province(*args); end

  # source://activerecord/7.2.2.1/lib/active_record/autosave_association.rb#162
  def validate_associated_records_for_barangays(*args); end

  class << self
    # source://activesupport/7.2.2.1/lib/active_support/callbacks.rb#70
    def __callbacks; end

    # source://activerecord/7.2.2.1/lib/active_record/reflection.rb#11
    def _reflections; end

    # source://activemodel/7.2.2.1/lib/active_model/validations.rb#71
    def _validators; end

    # source://activerecord/7.2.2.1/lib/active_record/enum.rb#167
    def defined_enums; end
  end
end

# source://pilipinas//lib/pilipinas/db/city.rb#0
module Pilipinas::Db::City::GeneratedAssociationMethods
  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/collection_association.rb#62
  def barangay_ids; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/collection_association.rb#72
  def barangay_ids=(ids); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#103
  def barangays; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#111
  def barangays=(value); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#32
  def build_province(*args, &block); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#36
  def create_province(*args, &block); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#40
  def create_province!(*args, &block); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#103
  def province; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#111
  def province=(value); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/belongs_to.rb#146
  def province_changed?; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/belongs_to.rb#150
  def province_previously_changed?; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#19
  def reload_province; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#23
  def reset_province; end
end

# source://pilipinas//lib/pilipinas/db/city.rb#0
module Pilipinas::Db::City::GeneratedAttributeMethods; end

# source://pilipinas//lib/pilipinas/db/province.rb#3
class Pilipinas::Db::Province < ::ActiveRecord::Base
  include ::Pilipinas::Db::Province::GeneratedAttributeMethods
  include ::Pilipinas::Db::Province::GeneratedAssociationMethods

  # source://activerecord/7.2.2.1/lib/active_record/autosave_association.rb#162
  def autosave_associated_records_for_cities(*args); end

  # source://activerecord/7.2.2.1/lib/active_record/autosave_association.rb#162
  def autosave_associated_records_for_region(*args); end

  # source://activerecord/7.2.2.1/lib/active_record/autosave_association.rb#162
  def validate_associated_records_for_cities(*args); end

  class << self
    # source://activesupport/7.2.2.1/lib/active_support/callbacks.rb#70
    def __callbacks; end

    # source://activerecord/7.2.2.1/lib/active_record/reflection.rb#11
    def _reflections; end

    # source://activemodel/7.2.2.1/lib/active_model/validations.rb#71
    def _validators; end

    # source://activerecord/7.2.2.1/lib/active_record/enum.rb#167
    def defined_enums; end
  end
end

# source://pilipinas//lib/pilipinas/db/province.rb#0
module Pilipinas::Db::Province::GeneratedAssociationMethods
  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#32
  def build_region(*args, &block); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#103
  def cities; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#111
  def cities=(value); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/collection_association.rb#62
  def city_ids; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/collection_association.rb#72
  def city_ids=(ids); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#36
  def create_region(*args, &block); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#40
  def create_region!(*args, &block); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#103
  def region; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#111
  def region=(value); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/belongs_to.rb#146
  def region_changed?; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/belongs_to.rb#150
  def region_previously_changed?; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#19
  def reload_region; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/singular_association.rb#23
  def reset_region; end
end

# source://pilipinas//lib/pilipinas/db/province.rb#0
module Pilipinas::Db::Province::GeneratedAttributeMethods; end

# source://pilipinas//lib/pilipinas/db/region.rb#3
class Pilipinas::Db::Region < ::ActiveRecord::Base
  include ::Pilipinas::Db::Region::GeneratedAttributeMethods
  include ::Pilipinas::Db::Region::GeneratedAssociationMethods

  # source://activerecord/7.2.2.1/lib/active_record/autosave_association.rb#162
  def autosave_associated_records_for_provinces(*args); end

  # source://activerecord/7.2.2.1/lib/active_record/autosave_association.rb#162
  def validate_associated_records_for_provinces(*args); end

  class << self
    # source://activesupport/7.2.2.1/lib/active_support/callbacks.rb#70
    def __callbacks; end

    # source://activerecord/7.2.2.1/lib/active_record/reflection.rb#11
    def _reflections; end

    # source://activemodel/7.2.2.1/lib/active_model/validations.rb#71
    def _validators; end

    # source://activerecord/7.2.2.1/lib/active_record/enum.rb#167
    def defined_enums; end
  end
end

# source://pilipinas//lib/pilipinas/db/region.rb#0
module Pilipinas::Db::Region::GeneratedAssociationMethods
  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/collection_association.rb#62
  def province_ids; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/collection_association.rb#72
  def province_ids=(ids); end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#103
  def provinces; end

  # source://activerecord/7.2.2.1/lib/active_record/associations/builder/association.rb#111
  def provinces=(value); end
end

# source://pilipinas//lib/pilipinas/db/region.rb#0
module Pilipinas::Db::Region::GeneratedAttributeMethods; end

# source://pilipinas//lib/pilipinas.rb#14
class Pilipinas::Error < ::StandardError; end

# source://pilipinas//lib/pilipinas/loader.rb#2
class Pilipinas::Loader
  class << self
    # source://pilipinas//lib/pilipinas/loader.rb#7
    def data_file; end

    # source://pilipinas//lib/pilipinas/loader.rb#3
    def run; end
  end
end

# source://pilipinas//lib/pilipinas/province.rb#2
class Pilipinas::Province < ::Pilipinas::Base
  # source://pilipinas//lib/pilipinas/province.rb#3
  def cities; end

  class << self
    # source://pilipinas//lib/pilipinas/province.rb#8
    def load_data; end
  end
end

# source://pilipinas//lib/pilipinas/region.rb#2
class Pilipinas::Region < ::Pilipinas::Base
  # source://pilipinas//lib/pilipinas/region.rb#3
  def provinces; end

  class << self
    # source://pilipinas//lib/pilipinas/region.rb#8
    def load_data; end
  end
end

# source://pilipinas//lib/pilipinas.rb#15
class Pilipinas::UnknownAttribute < ::Pilipinas::Error; end

# source://pilipinas//lib/pilipinas/version.rb#2
Pilipinas::VERSION = T.let(T.unsafe(nil), String)
