# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tailwindcss-rails` gem.
# Please instead update this file by running `bin/tapioca gem tailwindcss-rails`.


# source://tailwindcss-rails//lib/tailwindcss-rails.rb#1
module Tailwindcss; end

# source://tailwindcss-rails//lib/tailwindcss/commands.rb#4
module Tailwindcss::Commands
  class << self
    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#6
    def compile_command(debug: T.unsafe(nil), **kwargs); end

    # @return [Boolean]
    #
    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#30
    def rails_css_compressor?; end

    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#22
    def watch_command(always: T.unsafe(nil), poll: T.unsafe(nil), **kwargs); end
  end
end

# source://tailwindcss-rails//lib/tailwindcss/engine.rb#4
class Tailwindcss::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.2.2.1/lib/active_support/callbacks.rb#70
    def __callbacks; end
  end
end

# source://tailwindcss-rails//lib/tailwindcss/version.rb#2
Tailwindcss::VERSION = T.let(T.unsafe(nil), String)
