plugins = ["@trivago/prettier-plugin-sort-imports"]
semi = true
tabWidth = 2
singleQuote = false
trailingComma = "es5"
bracketSpacing = true
importOrderSeparation = true 
importOrderSortSpecifiers = true
