plugins = ["@trivago/prettier-plugin-sort-imports"]
singleQuote = false
bracketSpacing = true
trailingComma = "es5"
tabWidth = 2
semi = true
importOrderSeparation = true 
importOrderSortSpecifiers = true
