version: "3"
services:
  app:
    build:
      context: .
    container_name: fjc
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    # depends_on:
    #   - db
    volumes:
      - .:/app
    command: > 
      bash -c "rm -f tmp/pids/server.pid && 
      bin/rails db:migrate && 
      bin/rails db:seed RAILS_ENV=production && 
      bin/rails s -p 3000 -b '0.0.0.0'"
#   db:
#     image: "postgres:15.3-bookworm"
#     container_name: fjc_pg_db
#     ports:
#       - "5432:5432"
#     env_file:
#       - .env.prod
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_HOST_AUTH_METHOD: "trust"
#       POSTGRES_USER: ${DB_USER}
#       DATABASE_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - data:/var/lib/postgresql@15/data
# volumes:
#   data:
