# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::ActionsComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::ActionsComponent`.


class Carts::Item::ActionsComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
