# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::BaseComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::BaseComponent`.


class Carts::Item::BaseComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
