# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::CartStockWarningComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::CartStockWarningComponent`.


class Carts::Item::CartStockWarningComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
