# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::CheckboxComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::CheckboxComponent`.


class Carts::Item::CheckboxComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
