# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::DetailsComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::DetailsComponent`.


class Carts::Item::DetailsComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
