# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::QtyComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::QtyComponent`.


class Carts::Item::QtyComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
