# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::TotalpriceComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::TotalpriceComponent`.


class Carts::Item::TotalpriceComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
