# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::UnitpriceComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::UnitpriceComponent`.


class Carts::Item::UnitpriceComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
