# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::UpdateUrlComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::UpdateUrlComponent`.


class Carts::Item::UpdateUrlComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
