# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::VariantDropdownComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::VariantDropdownComponent`.


class Carts::Item::VariantDropdownComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
