# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carts::Item::VariantButtonComponent`.
# Please instead update this file by running `bin/tapioca dsl Carts::Item::VariantButtonComponent`.


class Carts::Item::VariantButtonComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
