# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ErrorMessageComponent`.
# Please instead update this file by running `bin/tapioca dsl ErrorMessageComponent`.


class ErrorMessageComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
