# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FlashComponent`.
# Please instead update this file by running `bin/tapioca dsl FlashComponent`.


class FlashComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
