# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PriceRangeComponent`.
# Please instead update this file by running `bin/tapioca dsl PriceRangeComponent`.


class PriceRangeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
