# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ProductComponent`.
# Please instead update this file by running `bin/tapioca dsl ProductComponent`.


class ProductComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
