# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SectionComponent`.
# Please instead update this file by running `bin/tapioca dsl SectionComponent`.


class SectionComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
