# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SectionLabelComponent`.
# Please instead update this file by running `bin/tapioca dsl SectionLabelComponent`.


class SectionLabelComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
