# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `StarRatingComponent`.
# Please instead update this file by running `bin/tapioca dsl StarRatingComponent`.


class StarRatingComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
