# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TabLinkComponent`.
# Please instead update this file by running `bin/tapioca dsl TabLinkComponent`.


class TabLinkComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
