name: RSpec Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: fjc
          POSTGRES_PASSWORD: password
          POSTGRES_DB: fjc_test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10ms
          --health-timeout 500ms
          --health-retries 15
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Setup Database
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB_NAME: fjc_test_db
          POSTGRES_PASSWORD: password
          POSTGRES_USERNAME: fjc
          POSTGRES_PORT: 5432
          RAILS_ENV: test
          PARALLEL_TEST_PROCESSORS: 2
        run: |
          cp config/database.test.yml config/database.yml
          bundle exec rake parallel:setup
      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB_NAME: fjc_test_db
          POSTGRES_PASSWORD: password
          POSTGRES_USERNAME: fjc
          POSTGRES_PORT: 5432
          RAILS_ENV: test
          PARALLEL_TEST_PROCESSORS: 2
        run: bundle exec rake parallel:spec
