# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Account::LayoutComponent`.
# Please instead update this file by running `bin/tapioca dsl Account::LayoutComponent`.


class Account::LayoutComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
