# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Account::SidenavUserComponent`.
# Please instead update this file by running `bin/tapioca dsl Account::SidenavUserComponent`.


class Account::SidenavUserComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
