# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Account::SidenavLinksComponent`.
# Please instead update this file by running `bin/tapioca dsl Account::SidenavLinksComponent`.


class Account::SidenavLinksComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
