# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Account::SidenavComponent`.
# Please instead update this file by running `bin/tapioca dsl Account::SidenavComponent`.


class Account::SidenavComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
